SET EXCLUSIVE ON
pathdbf = "D:\SHOP43\DBF\"
DO D:\FPD26\cpzero WITH pathdbf+"Mpartt.dbf", 866
DO D:\FPD26\cpzero WITH pathdbf+"Mprxop.dbf", 866
DO D:\FPD26\cpzero WITH pathdbf+"Mplast.dbf", 866
DO D:\FPD26\cpzero WITH pathdbf+"Mparam.dbf", 866
DO D:\FPD26\cpzero WITH pathdbf+"Mpartn.dbf", 866
DO D:\FPD26\cpzero WITH pathdbf+"Mregn.dbf", 866
DO D:\FPD26\cpzero WITH pathdbf+"Mkrist.dbf", 866
DO D:\FPD26\cpzero WITH pathdbf+"Mcompl.dbf", 866
DO D:\FPD26\cpzero WITH pathdbf+"J_brak.dbf", 866
DO D:\FPD26\cpzero WITH pathdbf+"Tr_brak.dbf", 866
DO D:\FPD26\cpzero WITH pathdbf+"Mrest.dbf", 866
DO D:\FPD26\cpzero WITH pathdbf+"Mproc.dbf", 866
DO D:\FPD26\cpzero WITH pathdbf+"Ampartt.dbf", 866
DO D:\FPD26\cpzero WITH pathdbf+"Amprxop.dbf", 866
DO D:\FPD26\cpzero WITH pathdbf+"Amplast.dbf", 866
DO D:\FPD26\cpzero WITH pathdbf+"Amparam.dbf", 866
DO D:\FPD26\cpzero WITH pathdbf+"Ampartn.dbf", 866
DO D:\FPD26\cpzero WITH pathdbf+"Amregn.dbf", 866
DO D:\FPD26\cpzero WITH pathdbf+"Amkrist.dbf", 866
DO D:\FPD26\cpzero WITH pathdbf+"Amcompl.dbf", 866
DO D:\FPD26\cpzero WITH pathdbf+"Amrest.dbf", 866
