using System;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using System.Collections;
using System.Collections.Generic;

namespace ARM2_dbcontrol.DataBase
{
    /// <summary>
    /// IMPORTANT: This class should never be manually edited.
    /// Generated by VlslV CodeSmith Template.
    /// This class is used to manage the TaskEntity object.
    /// </summary>
    public class TaskManager
    {

        VlslVConnection database;

        #region Constructors
        public TaskManager()
        {
            //
            // TODO: Add constructor logic here
            //
        }
        public TaskManager(VlslVConnection l_database)
        {
            database = l_database;
        }
        #endregion

        #region Methods

        public List<TaskEntity> List(String where, String order, Int32 page, Int32 size)
        {
            IDbCommand command = database.CreateCommand("GetTasksPage", true);

            database.AddCommandParameter(command, "@page",
                DbType.Int64, (Int64)page, ParameterDirection.Input);

            database.AddCommandParameter(command, "@rowcount",
                DbType.Int64, (Int64)size, ParameterDirection.Input);

            database.AddCommandParameter(command, "@where",
                DbType.String, where, ParameterDirection.Input);

            database.AddCommandParameter(command, "@orderby",
                DbType.String, order, ParameterDirection.Input);

            SqlDataReader reader = command.ExecuteReader() as SqlDataReader;
            List<TaskEntity> list = new List<TaskEntity>();
            while (reader.Read())
            {
                TaskEntity tasks = new TaskEntity();
                if (reader.GetValue(0) != DBNull.Value)
                    tasks.ID = reader.GetInt64(0);
                if (reader.GetValue(1) != DBNull.Value)
                    tasks.TaskName = reader.GetString(1);
                if (reader.GetValue(2) != DBNull.Value)
                    tasks.ComputerName = reader.GetString(2);
                if (reader.GetValue(3) != DBNull.Value)
                    tasks.TaskState = reader.GetString(3);
                if (reader.GetValue(4) != DBNull.Value)
                    tasks.DateIssued = reader.GetDateTime(4);
                if (reader.GetValue(5) != DBNull.Value)
                    tasks.DateComplete = reader.GetDateTime(5);
                if (reader.GetValue(6) != DBNull.Value)
                    tasks.DateUpdated = reader.GetDateTime(6);
                if (reader.GetValue(7) != DBNull.Value)
                    tasks.TaskParams = reader.GetString(7);
                if (reader.GetValue(8) != DBNull.Value)
                    tasks.TaskUser = reader.GetString(8);

                list.Add(tasks);
            }

            reader.Close();
            return list;
        }
        /// <summary>
        /// Task types list
        /// </summary>
        /// <returns></returns>
        public List<TaskEntity> ListTaskTypes()
        {
            IDbCommand command = database.CreateCommand("GetTaskTypesList", true);

            SqlDataReader reader = command.ExecuteReader() as SqlDataReader;
            List<TaskEntity> list = new List<TaskEntity>();
            while (reader.Read())
            {
                TaskEntity task = new TaskEntity();
                task.ID = reader.GetInt16(0);
                task.TaskName = reader.GetString(1);
                list.Add(task);
            }

            reader.Close();
            return list;

        }

        /// <summary>
        /// Create task and return taskID
        /// </summary>
        /// <param name="computerName"></param>
        /// <param name="taskName"></param>
        /// <param name="taskParams"></param>
        /// <returns></returns>
        public Object CreateTask(String computerName, String taskName, String taskParams, String taskUser)
        {
            IDbCommand command = database.CreateCommand("CreateTask", true);

            database.AddCommandParameter(command, "@ComputerName",
                DbType.String, computerName, ParameterDirection.Input);

            database.AddCommandParameter(command, "@TaskName",
                DbType.String, taskName, ParameterDirection.Input);

            database.AddCommandParameter(command, "@TaskParams",
                DbType.String, taskParams, ParameterDirection.Input);
            database.AddCommandParameter(command, "@TaskUser",
                DbType.String, taskUser, ParameterDirection.Input);

            return command.ExecuteScalar();
        }

        /// <summary>
        /// Return tas type id. When insertIfNotExists=1 insert if not exist
        /// </summary>
        /// <param name="taskName"></param>
        /// <param name="insertIfNotExists"></param>
        /// <returns></returns>
        public List<Int16> GetTaskTypeID(String taskName, Boolean insertIfNotExists)
        {
            IDbCommand command = database.CreateCommand("GetTaskTypeID", true);

            database.AddCommandParameter(command, "@TaskName",
                DbType.String, taskName, ParameterDirection.Input);

            database.AddCommandParameter(command, "@InsertIfNotExists",
                DbType.Boolean, insertIfNotExists, ParameterDirection.Input);

            List<Int16> list = new List<Int16>();
            SqlDataReader reader = command.ExecuteReader() as SqlDataReader;
            while (reader.Read())
            {
                list.Add(reader.GetInt16(0));
            }

            return list;
        }

        /// <summary>
        /// Select entity from database with this id
        /// </summary>
        /// <param name="computersID">ID</param>
        /// <returns>id</returns>
        public TaskEntity Get(Int64 tasksID)
        {
            IDbCommand command = database.CreateCommand("GetTaskByID", true);

            database.AddCommandParameter(command, "@ID",
                DbType.Int64, (Int64)tasksID, ParameterDirection.Input);

            TaskEntity task = new TaskEntity();
            SqlDataReader reader = command.ExecuteReader() as SqlDataReader;

            if (reader.Read())
            {

                if (reader.GetValue(0) != DBNull.Value)
                    task.ID = reader.GetInt64(0);
                if (reader.GetValue(5) != DBNull.Value)
                    task.TaskParams = reader.GetString(5);
                if (reader.GetValue(6) != DBNull.Value)
                    task.TaskName = reader.GetString(6);
                if (reader.GetValue(7) != DBNull.Value)
                    task.TaskUser = reader.GetString(7);
             
            }
            reader.Close();
            return task;
        }

        /// <summary>
        /// Возвращает IP-адрес компа, которому была выдана задача с заданным ID
        /// </summary>
        /// <param name="tasksID">ID адрес задачи</param>
        /// <returns></returns>
        public String GetIPAddressByTaskID(Int64 tasksID)
        {
            IDbCommand command = database.CreateCommand("GetIPAddressByTaskID", true);

            database.AddCommandParameter(command, "@ID",
                DbType.Int64, (Int64)tasksID, ParameterDirection.Input);

            SqlDataReader reader = command.ExecuteReader() as SqlDataReader;
            String ip = String.Empty;
            if (reader.Read())
            {

                if (reader.GetValue(0) != DBNull.Value)
                    ip = reader.GetString(0);

            }
            reader.Close();
            return ip;
        }



        /// <summary>
        /// Get count of records with filter
        /// </summary>
        /// <param name="where">where clause</param>
        /// <returns></returns>
        public Int32 Count(String where)
        {

            IDbCommand command = database.CreateCommand("GetTasksCount", true);

            database.AddCommandParameter(command, "@where",
                DbType.String, where, ParameterDirection.Input);


            return (Int32)command.ExecuteScalar();
        }

        /// <summary>
        /// Task states list
        /// </summary>
        /// <returns></returns>
        public List<String> ListTaskStates()
        {
            IDbCommand command = database.CreateCommand("GetTaskStatesList", true);

            SqlDataReader reader = command.ExecuteReader() as SqlDataReader;
            List<String> list = new List<String>();
            while (reader.Read())
            {
                if (reader.GetValue(0) != DBNull.Value)
                    list.Add(reader.GetString(0));
            }

            reader.Close();
            return list;
        }

        #endregion
    }
}

