//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCP.DAL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApproveStatus
    {
        public long ApproverStatusId { get; set; }
        public long ContractId { get; set; }
        public Nullable<long> ApproverTierId { get; set; }
        public Nullable<long> StatusId { get; set; }
    
        public virtual ApproverTier ApproverTier { get; set; }
        public virtual ApproveStatusType ApproveStatusType { get; set; }
        public virtual Contract Contract { get; set; }
    }
}
