//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCP.DAL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApproverTier
    {
        public ApproverTier()
        {
            this.ApproveStatus = new HashSet<ApproveStatus>();
        }
    
        public long ApproverTierId { get; set; }
        public long SalesPersonId { get; set; }
        public long ApproverId { get; set; }
        public long TierId { get; set; }
    
        public virtual Tier Tier { get; set; }
        public virtual ICollection<ApproveStatus> ApproveStatus { get; set; }
        public virtual User Approver { get; set; }
        public virtual User SalesPerson { get; set; }
    }
}
