//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCP.DAL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.AreaRoles = new HashSet<AreaRole>();
        }
    
        public long AreaId { get; set; }
        public string AreaName { get; set; }
    
        public virtual ICollection<AreaRole> AreaRoles { get; set; }
    }
}
