//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCP.DAL.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CCPEntities : DbContext
    {
        public CCPEntities()
            : base("name=CCPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<EndUser> EndUsers { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<RefreshToken> RefreshTokens { get; set; }
        public virtual DbSet<ApproveStatusType> ApproveStatusTypes { get; set; }
        public virtual DbSet<ContractStatusType> ContractStatusTypes { get; set; }
        public virtual DbSet<Tier> Tiers { get; set; }
        public virtual DbSet<ApproverTier> ApproverTiers { get; set; }
        public virtual DbSet<ApproveStatus> ApproveStatus1 { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<AreaRole> AreaRoles { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<AreaRoleView> AreaRoleViews { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
    }
}
