//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCP.DAL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Contracts = new HashSet<Contract>();
        }
    
        public long CustomerId { get; set; }
        public string CustomerName { get; set; }
        public long InternalCustomerId { get; set; }
    
        public virtual ICollection<Contract> Contracts { get; set; }
    }
}
