//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCP.DAL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public long MessageId { get; set; }
        public long RecipientId { get; set; }
        public Nullable<long> SalesPersonId { get; set; }
        public Nullable<long> ActionAuthorId { get; set; }
        public Nullable<long> PreviousContractStatusId { get; set; }
        public Nullable<long> CurrentContractStatusId { get; set; }
        public string Text { get; set; }
    
        public virtual ContractStatusType CurrentContractStatus { get; set; }
        public virtual ContractStatusType PreviousContractStatus { get; set; }
        public virtual User ActionAuthor { get; set; }
        public virtual User Recipient { get; set; }
        public virtual User SalesPerson { get; set; }
    }
}
