//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCP.DAL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.AreaRoles = new HashSet<AreaRole>();
            this.Users = new HashSet<User>();
        }
    
        public long RoleId { get; set; }
        public string RoleName { get; set; }
    
        public virtual ICollection<AreaRole> AreaRoles { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
