//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCP.DAL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tier
    {
        public Tier()
        {
            this.ApproverTiers = new HashSet<ApproverTier>();
        }
    
        public long TierId { get; set; }
        public long ApproverLevel { get; set; }
        public long TDGAMinValue { get; set; }
    
        public virtual ICollection<ApproverTier> ApproverTiers { get; set; }
    }
}
