//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Vba32CCService.rc
//
#define IDS_LOG_START                   101
#define IDS_LOG_SERVICE_STOP_ERROR      102
#define IDS_LOG_SERVICE_INSTALL_ERROR   103
#define IDS_LOG_SERVICE_INSTALL_SUCCESS 104
#define IDS_LOG_SERVICE_UNINSTALL_ERROR 105
#define IDS_LOG_SERVICE_UNINSTALL_SUCCESS 106
#define IDS_LOG_END                     107
#define IDS_MESSAGE_USAGE               108
#define IDS_APPTITLE                    109
#define IDS_LOG_SERVICE_START_ERROR     110
#define IDS_LOG_SERVICE_ALREADY_RUNNING 111
#define IDS_LOG_SOCKET_INIT_ERROR       112
#define IDS_LOG_DEBUG                   113
#define IDS_LOG_SERVICE_RESTART_SUCCESS 114
#define IDS_LOG_SERVICE_OPEN_ERROR      115
#define IDS_LOG_SERVICE_ALREADY_STOPPED 116
#define IDS_LOG_STATUS                  117
#define IDS_LOG_DEBUG_END               118
#define IDS_LOG_EXCEPTION               119
#define IDS_LOG_DUMP_SUCCESS            120
#define IDS_LOG_DUMP_ERROR              121
#define IDS_LOG_KEY_LICENSE             122
#define IDS_LOG_KEY_USER                123
#define IDS_LOG_KEY_ERROR               124
#define IDS_LOG_KEY_ERROR_NOT_FOUND     125
#define IDS_LOG_KEY_ERROR_BAD_KEY       126
#define IDS_LOG_KEY_ERROR_NO_SECTION    127
#define IDS_LOG_KEY_ERROR_EXPIRED       128
#define IDS_LOG_KEY_ERROR_INVALID_TIME  129
#define IDS_LOG_KEY_ERROR_ROLLED_BACK_TIME 130
#define IDS_LOG_INTEGRITY_OK            131
#define IDS_LOG_FATAL                   132
#define IDS_LOG_INTEGRITY_FAILED        133
#define IDS_LOG_INTEGRITY_CORRUPTED_FILE 134
#define IDS_LOG_COM_INIT_ERROR          135
#define IDS_LOG_PARSER_INIT_ERROR       136
#define IDS_LOG_PARSER_STARTED          137
#define IDS_LOG_PARSER_SHUTDOWN         138
#define IDS_LOG_UPDATE_STARTED          139
#define IDS_LOG_DB_CONNECT_OFF          140
#define IDS_LOG_UPDATE_FAILED           141
#define IDS_LOG_UPDATE_COMPLETE         142
#define IDS_LOG_UPDATE_INITIALIZED      143
#define IDS_LOG_UPDATE_FILELIST_DOWNLOAD_STARTED 144
#define IDS_LOG_UPDATE_FILELIST_RECIEVED 145
#define IDS_LOG_UPDATE_FILE_DOWNLOAD_STARTED 146
#define IDS_LOG_UPDATE_FILE_RECIEVED    147
#define IDS_LOG_UPDATE_FILE_DOWNLOAD_ERROR 148
#define IDS_LOG_UPDATE_FILELIST_DOWNLOAD_FAILED 149
#define IDS_LOG_UPDATE_FILE_REPLACE_ERROR 150
#define IDS_LOG_UPDATE_CONNECTION_ERROR 151
#define IDS_LOG_UPDATE_INIT_ERROR       152
#define IDS_LOG_UPDATE_START_ERROR      153
#define IDS_LOG_DB_CONNECT_ON           154
#define IDS_LOG_XML_PARSING_ERROR       155
#define IDS_LOG_XML_PARSED_OK           156
#define IDS_LOG_STARTING_NETWORK        157
#define IDS_LOG_SHUTTING_NETWORK        158

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        159
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
