//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Default3 {
    
    /// <summary>
    /// ScriptManager1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.ScriptManager ScriptManager1;
    
    /// <summary>
    /// UpdatePanel1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.UpdatePanel UpdatePanel1;
    
    /// <summary>
    /// TaskPanel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Controls_TaskPanel TaskPanel;
    
    /// <summary>
    /// SimpleTask1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Controls_SimpleTask SimpleTask1;
    
    /// <summary>
    /// SimpleTask2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Controls_SimpleTask SimpleTask2;
    
    /// <summary>
    /// SimpleTask3 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Controls_SimpleTask SimpleTask3;
    
    /// <summary>
    /// SimpleTask4 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Controls_SimpleTask SimpleTask4;
    
    /// <summary>
    /// SimpleTask5 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Controls_SimpleTask SimpleTask5;
    
    /// <summary>
    /// SimpleTask6 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Controls_SimpleTask SimpleTask6;
    
    /// <summary>
    /// SimpleTask7 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Controls_SimpleTask SimpleTask7;
    
    /// <summary>
    /// TaskOptionsDialog1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Controls_TaskOptionsDialog TaskOptionsDialog1;
    
    /// <summary>
    /// CreateProcessTask control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Controls_CustomizableTask CreateProcessTask;
    
    /// <summary>
    /// CreateProcessTaskOptions1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Controls_CreateProcessTaskOptions CreateProcessTaskOptions1;
    
    /// <summary>
    /// ConfigurePasswordTask control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Controls_CustomizableTask ConfigurePasswordTask;
    
    /// <summary>
    /// ConfigurePasswordTaskOptions1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Controls_ConfigurePasswordTaskOptions ConfigurePasswordTaskOptions1;
    
    /// <summary>
    /// RestoreFileFromQtnTask control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Controls_CustomizableTask RestoreFileFromQtnTask;
    
    /// <summary>
    /// RestoreFileFromQtnTaskOptions1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Controls_RestoreFileFromQtnTaskOptions RestoreFileFromQtnTaskOptions1;
    
    /// <summary>
    /// UninstallTask control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Controls_CustomizableTask UninstallTask;
    
    /// <summary>
    /// UninstallTaskOptions1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Controls_UninstallTaskOptions UninstallTaskOptions1;
    
    /// <summary>
    /// ProductInstallTask control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Controls_CustomizableTask ProductInstallTask;
    
    /// <summary>
    /// ProductInstallTaskOptions1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Controls_ProductInstallTaskOptions ProductInstallTaskOptions1;
    
    /// <summary>
    /// ChangeDeviceProtectTask control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Controls_CustomizableTask ChangeDeviceProtectTask;
    
    /// <summary>
    /// ChangeDeviceProtectTaskOptions1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Controls_ChangeDeviceProtectTaskOptions ChangeDeviceProtectTaskOptions1;
    
    /// <summary>
    /// TestTask control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Controls_CustomizableTask TestTask;
    
    /// <summary>
    /// TestTaskOptions1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Controls_TestTaskOptions TestTaskOptions1;
}
