//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfLogic.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.ITrackingDataManagers")]
    public interface ITrackingDataManagers {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingDataManagers/AddDeviceItemTo", ReplyAction="http://tempuri.org/ITrackingDataManagers/AddDeviceItemToResponse")]
        void AddDeviceItemTo(Crystal.DomainModel.TrackedDevice item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingDataManagers/RemoveDeviceItemFrom", ReplyAction="http://tempuri.org/ITrackingDataManagers/RemoveDeviceItemFromResponse")]
        void RemoveDeviceItemFrom(Crystal.DomainModel.TrackedDevice item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingDataManagers/GetTrackedDeviceItemsByUser", ReplyAction="http://tempuri.org/ITrackingDataManagers/GetTrackedDeviceItemsByUserResponse")]
        Crystal.DomainModel.TrackedDevice[] GetTrackedDeviceItemsByUser(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingDataManagers/AddBatchItemTo", ReplyAction="http://tempuri.org/ITrackingDataManagers/AddBatchItemToResponse")]
        void AddBatchItemTo(Crystal.DomainModel.TrackedBatch item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingDataManagers/RemoveBatchItemFrom", ReplyAction="http://tempuri.org/ITrackingDataManagers/RemoveBatchItemFromResponse")]
        void RemoveBatchItemFrom(Crystal.DomainModel.TrackedBatch item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackingDataManagers/GetTrackedBatchItemsByUser", ReplyAction="http://tempuri.org/ITrackingDataManagers/GetTrackedBatchItemsByUserResponse")]
        Crystal.DomainModel.TrackedBatch[] GetTrackedBatchItemsByUser(int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrackingDataManagersChannel : WcfLogic.ServiceReference2.ITrackingDataManagers, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrackingDataManagersClient : System.ServiceModel.ClientBase<WcfLogic.ServiceReference2.ITrackingDataManagers>, WcfLogic.ServiceReference2.ITrackingDataManagers {
        
        public TrackingDataManagersClient() {
        }
        
        public TrackingDataManagersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrackingDataManagersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrackingDataManagersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrackingDataManagersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddDeviceItemTo(Crystal.DomainModel.TrackedDevice item) {
            base.Channel.AddDeviceItemTo(item);
        }
        
        public void RemoveDeviceItemFrom(Crystal.DomainModel.TrackedDevice item) {
            base.Channel.RemoveDeviceItemFrom(item);
        }
        
        public Crystal.DomainModel.TrackedDevice[] GetTrackedDeviceItemsByUser(int userId) {
            return base.Channel.GetTrackedDeviceItemsByUser(userId);
        }
        
        public void AddBatchItemTo(Crystal.DomainModel.TrackedBatch item) {
            base.Channel.AddBatchItemTo(item);
        }
        
        public void RemoveBatchItemFrom(Crystal.DomainModel.TrackedBatch item) {
            base.Channel.RemoveBatchItemFrom(item);
        }
        
        public Crystal.DomainModel.TrackedBatch[] GetTrackedBatchItemsByUser(int userId) {
            return base.Channel.GetTrackedBatchItemsByUser(userId);
        }
    }
}
