// VbaTaskAssignment.idl : IDL source for VbaTaskAssignment
//

// This file will be processed by the MIDL tool to
// produce the type library (VbaTaskAssignment.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(4D8F6784-B7D3-46A4-BC29-9F4209AE93EA),
	dual,
	nonextensible,
	helpstring("ITaskService Interface"),
	pointer_default(unique)
]
interface ITaskService : IDispatch{
    [id(1), helpstring("method PacketSystemInfo")] HRESULT PacketSystemInfo([in] SAFEARRAY(INT64)* p_task_ids, [in] SAFEARRAY(DWORD)* p_ip_addresses);
    [id(2), helpstring("method PacketCreateProcess")] HRESULT PacketCreateProcess([in] SAFEARRAY(INT64)* p_task_ids, [in] SAFEARRAY(DWORD)* p_ip_addresses, [in] BSTR cmd_line);
    [id(3), helpstring("method PacketSendFile")] HRESULT PacketSendFile([in] SAFEARRAY(INT64)* p_task_ids, [in] SAFEARRAY(DWORD)* p_ip_addresses, [in] BSTR src_path, BSTR dst_path);
    [id(4), helpstring("method PacketConfigureSettings")] HRESULT PacketConfigureSettings([in] SAFEARRAY(INT64)* p_task_ids, [in] SAFEARRAY(DWORD)* p_ip_addresses, [in] BSTR settings);
    [id(5), helpstring("method PacketComponentState")] HRESULT PacketComponentState([in] SAFEARRAY(INT64)* p_task_ids, [in] SAFEARRAY(DWORD)* p_ip_addresses);
    [id(6), helpstring("method PacketCustomAction")] HRESULT PacketCustomAction([in] SAFEARRAY(INT64)* p_task_ids, [in] SAFEARRAY(DWORD)* p_ip_addresses, [in] BSTR options);
    [id(7), helpstring("method PacketCancelTask")] HRESULT PacketCancelTask([in] SAFEARRAY(INT64)* p_task_ids, [in] SAFEARRAY(DWORD)* p_ip_addresses);
    [id(8), helpstring("method PacketListProcesses")] HRESULT PacketListProcesses([in] SAFEARRAY(INT64)* p_task_ids, [in] SAFEARRAY(DWORD)* p_ip_addresses);
};
[
	uuid(33BF6BEB-0C79-425F-8E65-90E9E5269F79),
	version(1.0),
	helpstring("VbaTaskAssignment 1.0 Type Library")
]
library VbaTaskAssignmentLib
{
	importlib("stdole2.tlb");
	[
		uuid(DE6C9F17-C542-4B66-B253-ABFB2B4DF397),
		helpstring("TaskService Class")
	]
	coclass TaskService
	{
		[default] interface ITaskService;
	};
};
