//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testangularjs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableModal
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTimeOffset DateGreate { get; set; }
        public Nullable<System.DateTimeOffset> DateChange { get; set; }
        public string Description { get; set; }
    }
}
