//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldBullion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListOfMetal
    {
        public ListOfMetal()
        {
            this.PriceOfMetal = new HashSet<PriceOfMetal>();
        }
    
        public int Id { get; set; }
        public string Name_Metal { get; set; }
    
        public virtual ICollection<PriceOfMetal> PriceOfMetal { get; set; }
    }
}
